language: node_js

os:
  - 'linux'
  
dist: 'trusty'

cache:
  directories:
  - node_modules

node_js:
  - "8"

install:
  - npm install

script:
  - npm run build
  - npm run test:cover:CI

notifications:
  email:
    on_success: never
    on_failure: always