export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const FETCH_AGAST_REQUEST = 'FETCH_AGAST_REQUEST';
export const FETCH_AGAST_SUCCESS = 'FETCH_AGAST_SUCCESS';
export const FETCH_AGAST_FAILURE = 'FETCH_AGAST_FAILURE';

export const SAVE_AGAST_REQUEST = 'SAVE_AGAST_REQUEST';
export const SAVE_AGAST_SUCCESS = 'SAVE_AGAST_SUCCESS';
export const SAVE_AGAST_FAILURE = 'SAVE_AGAST_FAILURE';