export const FETCH_AGAST_REQUEST = 'FETCH_AGAST_REQUEST';
export const FETCH_AGAST_SUCCESS = 'FETCH_AGAST_SUCCESS';
export const FETCH_AGAST_FAILURE = 'FETCH_AGAST_FAILURE';

export const FETCH_LIST_AGAST_REQUEST = 'FETCH_LIST_AGAST_REQUEST';
export const FETCH_LIST_AGAST_SUCCESS = 'FETCH_LIST_AGAST_SUCCESS';
export const FETCH_LIST_AGAST_FAILURE = 'FETCH_LIST_AGAST_FAILURE';


export const SAVE_AGAST_REQUEST = 'SAVE_AGAST_REQUEST';
export const SAVE_AGAST_SUCCESS = 'SAVE_AGAST_SUCCESS';
export const SAVE_AGAST_FAILURE = 'SAVE_AGAST_FAILURE';